name: QOLCommands
version: '1.1.1'
main: at.zDreamiii.qOLCommands.QOLCommands
api-version: '1.21'

commands:
  Feed:
    description: Fills your hunger bar completely
    usage: /feed
    permission: qolcommands.feed
    permission-message: "§cYou do not have permission to use this command!"
  Heal:
    description: Restores your health completely
    usage: /heal
    permission: qolcommands.heal
    permission-message: "§cYou do not have permission to use this command!"
  Repair:
    description: Fully repairs your items
    usage: /repair
    permission: qolcommands.repair
    permission-message: "§cYou do not have permission to use this command!"
  Gamemode:
    description: Change your game mode like before using numbers (or names)
    usage: /gamemode <0-3|name>
    permission: qolcommands.gamemode
    permission-message: "§cYou do not have permission to use this command!"

permissions:
  qolcommands.*:
    description: Grants access to all QOLCommands commands
    default: op
    children:
      qolcommands.feed: true
      qolcommands.heal: true
      qolcommands.repair: true
      qolcommands.gamemode: true
